### ISSUE TITLE
multiple explosions onscreen ramp up the tri count to 1.5m 

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#106]
<a href="https://github.com/alejandro-2awesome"><img src="https://avatars.githubusercontent.com/u/8968755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alejandro-2awesome](https://github.com/alejandro-2awesome)**
_Friday Sep 04, 2015 at 08:10 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/106_

---

@maxHey: I just noticed that multiple explosions onscreen ramp up the tri count to 1.5m and more sometimes, maybe we decrease the poly density in them if thats possible?

**Comment by david-2awesome** [comment]
Marked as enhancement as it doesn't seem to be a problem for performance now.

**Comment by alejandro-2awesome** [comment]
Fixed on NX performance improvements
