### ISSUE TITLE
Add achievements

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#11]
<a href="https://github.com/2awesomestudio"><img src="https://avatars.githubusercontent.com/u/9165009?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [2awesomestudio](https://github.com/2awesomestudio)**
_Sunday Oct 12, 2014 at 21:35 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/11_

---

**Comment by david-2awesome** [comment]
Traced in Trello
