### ISSUE TITLE
Destruction percentage above 100%

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#111]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Thursday Sep 17, 2015 at 19:40 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/111_

---

The report screen shows sometimes more than 100% destruction percentage.

**Comment by david-2awesome** [comment]
Destruction is not used anymore on the level  report
