### ISSUE TITLE
Heat wave effect on explosions, doesnt work on Mac & Linux

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#114]
<a href="https://github.com/alejandro-2awesome"><img src="https://avatars.githubusercontent.com/u/8968755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alejandro-2awesome](https://github.com/alejandro-2awesome)**
_Tuesday Sep 22, 2015 at 02:19 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/114_

---

This problem only happen in the right side camera

@maxHey @StanislavBotev do you have any ideas / suggestions where to start looking for this bug?

**Comment by alejandro-2awesome** [comment]
This problem is caused because of shadows being projected on meshes that they should not receive them, specially on world 2.

They need a deep clean up

**Comment by hexxellor** [comment]
Verified Fix On v0.8.4.1
