### ISSUE TITLE
Customizable button mapping

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#131]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Friday Nov 06, 2015 at 14:04 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/131_

---

**Comment by david-2awesome** [comment]
Traced in Trello
