### ISSUE TITLE
The cooldown on teleporting feels very forced

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#145]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Sunday Dec 06, 2015 at 14:46 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/145_

---

Adrian de Jongh comment (To be confirmed what's the issue)

**Comment by david-2awesome** [comment]
Cooldown removed
