### ISSUE TITLE
Control graphic options via script and option menu

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#146]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Sunday Dec 06, 2015 at 19:44 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/146_

---

Add controls via script first (then create a graphics option menu) with at least:
- Resolution
- Full Screen On/off
- VSync
- Deferred Rendering / Forward Rendering
- Real-time lights On/Off
- Particles (High/Low) 
- Antialiasing
- etc.

**Comment by david-2awesome** [comment]
Graphic options are now in game
