### ISSUE TITLE
Make power ups turn into Points Item if already enabled

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#171]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Wednesday Dec 16, 2015 at 09:43 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/171_

---

If the player already has a certain power up enabled this power up should not appear again. Instead a Bonus Points Item should appear.

**Comment by alejandro-2awesome** [comment]
Not valid till we decide powers up system
