### ISSUE TITLE
Add Unity Analytics

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#196]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Tuesday Jan 26, 2016 at 14:21 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/196_

---

**Comment by david-2awesome** [comment]
Added
