### ISSUE TITLE
Input should not be allowed until blinds are opened

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#215]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Wednesday Apr 20, 2016 at 18:00 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/215_

---

**Comment by david-2awesome** [comment]
Fixed
