### ISSUE TITLE
Pausing and exiting

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#216]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Wednesday Apr 20, 2016 at 18:01 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/216_

---

When pausing and exiting a level, the time will be re-enabled and you can see just before the blinds close the game moving.

**Comment by david-2awesome** [comment]
Closed, player does not die in that period.
