### ISSUE TITLE
chromatic aberration stuck sometimes when you die

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#225]
<a href="https://github.com/alejandro-2awesome"><img src="https://avatars.githubusercontent.com/u/8968755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alejandro-2awesome](https://github.com/alejandro-2awesome)**
_Sunday May 22, 2016 at 18:13 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/225_

---

**Comment by david-2awesome** [comment]
Chromatic aberration is not present now. Screenshake does not get stuck anymore.
