### ISSUE TITLE
Game is too difficult in 2 player mode

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#233]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Monday May 23, 2016 at 19:12 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/233_

---

2 player mode is too difficult after testing it at Indievelopment. Most players where dying CRASHING against the environment. 

Two options are possible:

1) Make 5 lives the default value in 2 player mode.
2) Make the game check if the player is going to collide when jumping and do not allow them to jump if this is the case with some effect and SFX.

**Comment by david-2awesome** [comment]
5 lives and regenerative shields now.
