### ISSUE TITLE
Players draining energy too fast in 2 player mode

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#234]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Monday May 23, 2016 at 19:13 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/234_

---

When both players are on the same dimension they were draining energy too fast. Reduce the value.

**Comment by david-2awesome** [comment]
Balanced.
