### ISSUE TITLE
Bullets not hitting player 2 in inverse

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#235]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Monday May 23, 2016 at 19:24 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/235_

---

In 2 player mode sometimes the player 2 doesn't get hit by Ashajul bullets when on Inverse.

**Comment by david-2awesome** [comment]
It works now.
