### ISSUE TITLE
Game should indicate clearly who and where died in 2 player mode

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#236]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Monday May 23, 2016 at 19:26 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/236_

---

to discuss ideas

**Comment by david-2awesome** [comment]
Traced in Trello
