### ISSUE TITLE
Fix Ashajul Blade

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#244]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Thursday Jun 02, 2016 at 12:02 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/244_

---

After Stan added the new animations the Ashajul Blade doesn't not work properly anymore.

**Comment by david-2awesome** [comment]
MK1 and MK3 working, MK2 needs to be implemented but bug is fixed.
