### ISSUE TITLE
Create a new Enemy Squadron object

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#246]
<a href="https://github.com/david-2awesome"><img src="https://avatars.githubusercontent.com/u/9167580?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [david-2awesome](https://github.com/david-2awesome)**
_Thursday Jun 02, 2016 at 12:07 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/246_

---

For the end miniboss areas create an object where a list of spawners that are in the level can be dragged and dropped. The Squadron Object will activate the spawners in the list in a loop of a given time. Add the options to loop, loop in ping-pong mode, and the loop times. More ideas are welcome.

**Comment by david-2awesome** [comment]
Closed as already captured in issue https://github.com/2awesomestudio/DimensionDriveIssueTracker/issues/288
