### ISSUE TITLE
SF dying process when player dies gets error

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#250]
<a href="https://github.com/alejandro-2awesome"><img src="https://avatars.githubusercontent.com/u/8968755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alejandro-2awesome](https://github.com/alejandro-2awesome)**
_Saturday Jun 04, 2016 at 00:14 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/250_

---

1- Kill SF at the end of level 1_2
2- Die quick
3- See the error:

Coroutine couldn't be started because the the game object 'SF_CODE(Clone)002' is inactive!
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
SF_MK_Control:OnWaitBeforeMoving() (at Assets/Scripts/Enemies/(SF) Ashajul Starfire/SF_MK_Control.cs:69)
EnemyPlayGivenAnim:OnEndAnimation() (at Assets/Scripts/EnemyActions/EnemyPlayGivenAnim.cs:63)
EnemyPlayGivenAnim:OnUpdate(Single) (at Assets/Scripts/EnemyActions/EnemyPlayGivenAnim.cs:38)
DimensionDrive.Core.GameLogic:FixedUpdate() (at Assets/Scripts/Core/GameLogic.cs:49)

**Comment by david-2awesome** [comment]
Fixed
