### ISSUE TITLE
Add correct control binding for Wii-U pro controller

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#262]
<a href="https://github.com/alejandro-2awesome"><img src="https://avatars.githubusercontent.com/u/8968755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alejandro-2awesome](https://github.com/alejandro-2awesome)**
_Wednesday Jun 15, 2016 at 21:46 GMT_
_Originally opened as https://github.com/2awesomestudio/DimensionDrive/issues/262_

---

**Comment by david-2awesome** [comment]
Closed as already traced in Trello https://trello.com/c/rn0RtR8Z
