### ISSUE TITLE
Drift effect on the wrong side

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#311]
The Drift "shield" effect around the Manticore sometimes appears in the wrong direction. To reproduce chain several Drifts in both directions. Last image shows the proper behaviour, first two show wrong behaviour.

![image](https://cloud.githubusercontent.com/assets/9167580/17681951/e92cd51c-6348-11e6-821a-2d40cbdc3d0f.png)

![image](https://cloud.githubusercontent.com/assets/9167580/17681956/edd941c2-6348-11e6-94e3-2d1ffb04d9b1.png)

![image](https://cloud.githubusercontent.com/assets/9167580/17681958/f4549240-6348-11e6-877a-248b6e155716.png)

**Comment by alejandro-2awesome** [comment]
It looks nice as it is
