### ISSUE TITLE
Jump point not being shown sometimes

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/DimensionDriveIssueTracker#341]
Description

The jump point is sometimes not being shown as it goes below the environment
@StanislavBotev can you make the art to be placed all the time on top of everything ( Y-AXIS). Only the art part, not the whole object.

Reproduction Steps
Play levels on World 2
Check how sometimes the jump effect disappears

Build
0.7.2.1

Screenshot

**Comment by david-2awesome** [comment]
Still not fixed. Jump point should be higher.
![image](https://cloud.githubusercontent.com/assets/9167580/25554415/3698658e-2ccd-11e7-9d21-7435e26c8ce6.png)

**Comment by alejandro-2awesome** [comment]
Fixed
