### ISSUE TITLE
Mini-bosses jump on top of it and being destroyed

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/DimensionDriveIssueTracker#344]
Description

If you play any miniboss of W1, jumping on top of it destroys it and that is cheating as you can finish the level just doing so.

Reproduction Steps
Play any level from W1 (1-3)
Arrive to mini-boss area
Jump on top of it. 
Check how only 1 shield is deducted

Build
0.7.2.1

Screenshot

**Comment by david-2awesome** [comment]
Fixed.
