### ISSUE TITLE
Using inverse in Orb areas could make the scroll not resume

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#364]
**Description**
When you're in world 2-3 you eventually enter the orb zone: (just after the first checkpoint).
if you destroy the green orb before the screen (use inverse drive it will slow down scrolling, you can get it destroyed even before the first laser hit you) has stopped scrolling (which I managed to do here) you're stuck in limbo! the gate opened but you can't progress.

I can reproduce this bug reliably every time! I'm only able to progress when I wait for the screen to stop scrolling altogether before I even attempt to destroy the green orb.

**Reproduction Steps**
Get to orb in word 2-3
Use reverse before seeing the lasers
Observe how you can destroy the orb before the scroll stops

**Build**
0.8.0.1

**Screenshoot**
![image](https://cloud.githubusercontent.com/assets/9165009/23095822/d0ce416c-f610-11e6-9c39-02b6c7237e30.png)

**Comment by 2awesomestudio** [comment]
Fixed by assigning the camera collider to the orb controller

**Comment by david-2awesome** [comment]
Checked.
