### ISSUE TITLE
GameLogic raises an error

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#366]
Description
As objects get deleted from our gamelogic, sometimes they do so in the middle of an update cycle (raising an error, and producing unexpected behaviors

Reproduction Steps
1- Play any level for a while
2- chec the console and see some error as follows:
FixedUpdate ErrorArgument is out of range.

Build
0.8.0.1

**Comment by 2awesomestudio** [comment]
Check if the current iterator is still valid

**Comment by hexxellor** [comment]
Verified as fixed.
