### ISSUE TITLE
Game over screen wrong input

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#369]
Description
The game over screen uses "Fire" to accept the options of its menu instead of "Accept" button (A/Enter).

Reproduction Steps
Play any level and die until Game Over.
Try to select any option with the default "Accept" button.

Build
0.8.1.22

**Comment by 2awesomestudio** [comment]
Fixed (as default "Accept button being Jump"

**Comment by hexxellor** [comment]
Verified as fixed.
