### ISSUE TITLE
Weapons leave purple stuff on impact

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#370]
Description
Weapons leave some purple stuff on screen after they impact. This happens specially against bosses when the screen is static.

Reproduction Steps
Play level 1-3 (for example) arrive to the box and fire at it continuously from close distance.
After a while some purple marks will be on the screen.

Build
0.8.1.22
![image](https://cloud.githubusercontent.com/assets/9167580/25537737/10cf28d4-2c40-11e7-9ee4-a9e754c74859.png)

**Comment by david-2awesome** [comment]
Just checked in engine. It appears to be a problem of a lot of Bullet Splash objects getting stuck there.

![image](https://cloud.githubusercontent.com/assets/9167580/25554093/6c4865f6-2cc5-11e7-95fd-14d157d0829f.png)

**Comment by hexxellor** [comment]
Verified Fixed In v0.8.2.1
