### ISSUE TITLE
Shield not regenerating after first death

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#371]
Description
When playing in Normal difficulty, shields are not regenerating after you lose a life.

Reproduction Steps
Play any level in Normal mode.
Die and lose one life.
Observe how after receiving damage your shields do not regenerate anymore.

Build
0.8.1.22

**Comment by 2awesomestudio** [comment]
Fixed by re-adding the timer after the respawn process

**Comment by hexxellor** [comment]
Verified as fixed.
