### ISSUE TITLE
Info panel box not showing proper info

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#373]
Description

The info panel box in the level select shows the level points instead of the Total Score, also rank does not seem to be proper. Not sure about data cubes. In the example screenshot you can see the score and rank do not match.

Reproduction Steps
Complete any level and check your level points and total score.
Go to the level select screen.
You will see the info panel shows the level points instead of total score.

Build
0.8.1.22

Screenshot
![image](https://cloud.githubusercontent.com/assets/9167580/25556516/56e83a36-2cfe-11e7-9ce3-92320bd9ad03.png) 
![image](https://cloud.githubusercontent.com/assets/9167580/25556537/8edda520-2cfe-11e7-9df2-f5050dda56ca.png)

**Comment by 2awesomestudio** [comment]
Fixed by saving the correct information on levelreport screen

**Comment by hexxellor** [comment]
This has been verified as fixed.
