### ISSUE TITLE
Info panel showing default info after completing a level

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#374]
Description

The info panel box in the level select shows me the default information (info when level is not completed) after I have completed the level and unlocked the next one. 

Reproduction Steps
I don't know how to reproduce this one.

Build
0.8.1.22

Screenshot
![image](https://cloud.githubusercontent.com/assets/9167580/25556592/80adcefc-2cff-11e7-9c9a-89c1aeada340.png)

**Comment by 2awesomestudio** [comment]
@david-2awesome Have you finish the level, or just unlocked them?

**Comment by alejandro-2awesome** [comment]
Fixed
