### ISSUE TITLE
Trackers bug out after dying

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#375]
Description
Sometimes Trackers will spawn pointing up and won't do anything. Just float there forever.

Reproduction Steps
Play level 1-3 and reach the second checkpoint.
Stay on the left side.
Die before reaching the 3rd checkpoint.
Some trackers will be bugged and the console will throw the following error:

NullReferenceException: Object reference not set to an instance of an object
DimensionDrive.Enemies.Actions.EnableObjectAction.ActionStart () (at Assets/Source/EnemyActions/EnableObjectAction.cs:16)
DimensionDrive.Enemies.Actions.EnemyActionManager.OnStepActionsStart () (at Assets/Source/EnemyActions/EnemyActionManager.cs:109)
DimensionDrive.Enemies.Actions.EnemyActionManager.OnManagerStart () (at Assets/Source/EnemyActions/EnemyActionManager.cs:39)
DimensionDrive.Enemies.Control.AT_MK_Control.OnStart () (at Assets/Source/Enemies/Control/AT_MK_Control.cs:31)
DimensionDrive.Enemies.Spawners.AT_MK_Spawner.OnStartNextEnemy () (at Assets/Source/Enemies/Spawners/AT_MK_Spawner.cs:103)
DimensionDrive.Enemies.Spawners.AT_MK_Spawner.SpawnEnemies () (at Assets/Source/Enemies/Spawners/AT_MK_Spawner.cs:82)
EnemySpawnerBase.OnSpawn () (at Assets/Source/Enemies/Spawning/EnemySpawnerBase.cs:179)
EnemySpawnerBase.OnTriggerExit (UnityEngine.Collider other) (at Assets/Source/Enemies/Spawning/EnemySpawnerBase.cs:168)

Build
0.8..1.22

Screenshot
![image](https://cloud.githubusercontent.com/assets/9167580/25556991/40db50e8-2d08-11e7-9e5f-ead3757e9a32.png)

**Comment by 2awesomestudio** [comment]
I think it has been fixed. The problem was that the trail object was disabled on the next spawn iteration, although there was a null object when trying to enable it.

**Comment by hexxellor** [comment]
This has been verified.
