### ISSUE TITLE
Boss dead does not produce screenshake

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/DimensionDriveIssueTracker#378]
Description
When killing the final boss of 1-4, there is no screen shake 

Reproduction Steps

Play 1-4
Kill the boss
See how the explosion does not produces a screenshake

Build
0.8.1.3

**Comment by alejandro-2awesome** [comment]
Added explosion as big enemies.It would be nice to have a sequential explosion ans boss of World 2. for now this would do the trick

**Comment by hexxellor** [comment]
Verified Fixed In v0.8.2.1
