### ISSUE TITLE
Game skipping levels

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#379]
### Description

After completing a level the game jumps to an incorrect level farther in the game than it should (even if the level is still locked). For example from 1-1 directly to 2-4.

### Reproduction Steps
1. Play and finish level 1-1
2. When the miniboss dies start pressing A repeatedly.
3. The game will show some lag, the level report will skip and the bug will be triggered.

### Build

_**0.8.1.3**_

### Screenshot

_*_
![image](https://cloud.githubusercontent.com/assets/9167580/25781352/703889b4-3339-11e7-91a3-cbe32a241f8a.png)
_

**Comment by hexxellor** [comment]
Verified Fixed In v0.8.4.1
