### ISSUE TITLE
Life bars appear with wrong value after death

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#381]
### Description

After player death the Enemy Life bars appear with the last value that the enemy had before death.

### Reproduction Steps
1. Play level 1-1 and arrive to the mini-boss.
2. Shoot at the boss for a while until life bar is half full.
3. Die.
4. When you arrive to the boss after respawn the life bar will show half full.

### Build

_**0.8.1.3**_

### Screenshot
No screenshot needed.

**Comment by hexxellor** [comment]
Verified Fixed In v0.8.4.1
