### ISSUE TITLE
Blade MK3 enemies does not flash on impact

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/DimensionDriveIssueTracker#382]
Description
When shooting to Blade MK3 this enemy does not flash

Reproduction Steps
Play level 1-1
Arrive to end-boss (BL_MK3)
Shott and observe they do not flash

Build
0.8.1.3

**Comment by alejandro-2awesome** [comment]
The problem is that this enemy object does not have attached the script MeshFlashController on the meses that they need to:
![image](https://cloud.githubusercontent.com/assets/8968755/25948012/183eaa2e-3652-11e7-9de0-b7ffa61f7bba.png)


Please review MK1, MK2, and MK3 and add this script when needed. 
1- Try to avoid small parts
2- Add the script on the object it has a mesh we want to make flash

**Comment by david-2awesome** [comment]
Scripts added, the enemy still does NOT flash on impact..

**Comment by alejandro-2awesome** [comment]
Fixed assigning the collider object to correct tag and layer

**Comment by david-2awesome** [comment]
Fixed
