### ISSUE TITLE
Pulse Cannon Description Confusing

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#386]
### Description

When choosing weapons at the start of a game, when you select Pulse Cannon the description claims it's multidirectional, however the picture shows only one shot which shoots forward. When the game starts, as depicted, only one shot comes from the front of the ship which isn't multidirectional.

I understand that one you upgrade the weapon it does shoot out of the sides, but the picture and start of the level (basic weapon, w/o upgrades) both tend to disagree with the description.

### Reproduction Steps
1. At the start of a new game, select the Pulse Cannon.
2. Observe the description and picture.
3. Start the game and observe the shot itself.

### Build
Current development build as of 0.8.1.41

**Comment by david-2awesome** [comment]
Closed by fixing the description.
