### ISSUE TITLE
No Way To Delete Data From Save-Game Slots

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#387]
### Description

Currently there is no way to delete data from the save-game slots unless the user manually finds the save-data on the drive and removes it by hand, risking deleting the wrong one. Also, if cloud-saving is enabled at some point this might become a bigger issue.

The main reason I mention this is because let's say a user fills up all of the slots with games based on the Normal difficulty and later wanted to start one based on Hard, Extreme, etc. At this time there is no way to do that.

### Reproduction Steps
1. Fill all slots with save games.
2. Observe there is no way to remove one or change the difficulty.

### Build
Game Version - Build 0.8.1.41
OS - All Supported

**Comment by alejandro-2awesome** [comment]
Implemented on 0.8.3.X

**Comment by hexxellor** [comment]
Verified Fixed In Latest Build (v0.8.4.1)
