### ISSUE TITLE
Game Ends With A Black Screen

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#395]
### Description

I assume this is a known issue, but when the player finishes the current level 2_4, the screen goes black and the user cannot do anything except for close the game in order to force it to start over at the menus.

### Reproduction Steps
1. Proceed to the end of level 2_4 (Normal was tested)
2. After clearing the level a black screen shows up and the user cannot do anything. Keypresses are ignored.

### Build
Game Version - Build 0.8.1.41
OS - Mac OS X Tested.

**Comment by alejandro-2awesome** [comment]
Now the game ends properly, with the credits scene :)
