### ISSUE TITLE
VSync Menu Option Text Incorrect

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#402]
### Description

In the settings menu for graphics the VSync option now says something similar to "TDD_MAIN_MENU_ON". I can't tell for sure because it's cut off on the edge of the screen. 😉 

I'm guessing this is just a localized string which isn't loading because of a typo or something based on the text but not 100% sure obviously.

### Reproduction Steps
1. Start the game.
2. Go to the "Options" menu and then the "Video Settings" menu.
3. Notice the text for the VSync setting. I can't change the setting either. It's stuck on this text as far as I can tell.

### Build
Game: Development Build v0.8.2.0
OS Tested: Mac OS X 10.12.5 (16F73)

### Screenshot

![vsync option while in window mode](https://user-images.githubusercontent.com/892633/28116912-c4a7f50a-66d0-11e7-95f5-d2ecb6fbc142.png)

**Comment by 2awesomestudio** [comment]
Fixed on 0.8.2.1

**Comment by hexxellor** [comment]
Verified Fixed On 0.8.2.1
