### ISSUE TITLE
Switches do not activate when they are about to leave the screen

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#403]
Description
When switches are about to leave the screen player bullets will not activate them.

Reproduction Steps
Play level 2-3 and wait until the first switch is almost leaving the screen.
Fire at it and you will see it does not activate.

Build
0.8.21
The first build in which this bug was found

Screenshot

_*Attach the pic here if necessary or available
![image](https://user-images.githubusercontent.com/9167580/28384752-16ca5ae4-6cc6-11e7-9e27-2b7c4456f334.png)

**Comment by alejandro-2awesome** [comment]
Fixed by putting a bit lower the weapons despawner collider
