### ISSUE TITLE
No Teleportation Warning Graphic In Level 1-2 and 1-4

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#406]
### Description

When using the Normal difficulty, there should be a graphical indicator that appears on the ship to indicate that if you teleport you will be on top of a structure, causing you to lose your ship. It looks like this:
![warning](https://user-images.githubusercontent.com/892633/28739755-5f24de32-73c3-11e7-854c-a08cef608111.png)

On levels 1-2 and 1-4, this graphic appears to be missing.

NOTE: This may occur on other difficulties. At this time I've only tested it on Normal.

### Reproduction Steps
1. Start the game, select level 1-2.
2. On one side of the screen move the ship so that if you teleport you would die.
3. Observe no graphics on the ship.
4. Do the same thing (steps 1-3) on level 1-4.
5. Now do it on any other level and observe that the graphics are there for those levels.

### Build
Game: Development Build v0.8.2.1
OS: Tested On Mac OS X v10.12.6

### Screenshot

Here is a screen shot showing the graphics missing at the start of level 1-2:
![level 1-2](https://user-images.githubusercontent.com/892633/28739765-76267938-73c3-11e7-8fa0-7d144693793e.png)

Here is a screen shot showing the graphics missing at the start of level 1-4:
![level 1-4](https://user-images.githubusercontent.com/892633/28739759-6879dae6-73c3-11e7-9952-16c6b56381f8.png)

**Comment by alejandro-2awesome** [comment]
fixed on latest builds
