### ISSUE TITLE
Graphics Regression On Latest Build (0.8.2.1 - Windows/Mac)

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#407]
### Description

On the latest development build the graphics have reverted to a state which are not correct.

The graphics issue causes the images to look strange, but also very dark which makes it incredibly hard to navigate levels. See the screenshots for more information.

NOTE: The graphics issues look similar to those seen in https://github.com/2awesomestudio/DimensionDriveIssueTracker/issues/376 but the glitches in that issue are not present. In other words, the colors, lighting, etc. look similar, but the screen is visible and not partially off-screen, etc.

### Reproduction Steps
1. Start the game and select level 1-1.
2. Observe the strange lighting/flashing.
3. Proceed to play the level.
4. Observe the objects in the level are very dark and hard to see.

### Build
Game: Development Build v0.8.2.1
OS: Tested On Mac OS X v10.12.6 and Windows 8.1 (Unable to test Linux due to another issue at this time).

### Screenshot

Movie showing the graphics at the start of level 1-1 looking strange:
[Level 1-1 Graphics.zip](https://github.com/2awesomestudio/DimensionDriveIssueTracker/files/1184547/Level.1-1.Graphics.zip)

Image showing background graphics looking very dark and hard to tell apart from objects your ship can hit in 1-1:
![dark graphics 1-1](https://user-images.githubusercontent.com/892633/28741046-e2f4c0c8-73d3-11e7-91a2-a6aa4adf83db.png)

**Comment by alejandro-2awesome** [comment]
Fixed on latest builds
