### ISSUE TITLE
Pressing Buttons Out Of Order Cause Tutorial Flow Bugs

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#408]
### Description

The flow of the tutorial can be messed up by pressing buttons that are not expected by the game.

There are numerous issues you can cause, so this listing will try to detail at least a couple of them.

Example Issue 1
Pressing the warp/teleport button on the controller (B) twice during the tutorial (before you can actually teleport to the right side) causes the tutorial to start scrolling and dropping items uncontrollably.

Example Issue 2
Pressing START and trying to stop the tutorial when a tutorial dialog is about to appear causes overlapping dialogs which also causes issues with the tutorial.

There are many other issues that can be caused by pressing buttons out of order. Too many to list in a reasonable amount of time, but since they all seem to be caused by the same issue I'll leave it as this one GitHub issue.

NOTE: Apparently this can cause issues that continue on the story screen between level 1-0 and 1-1 but making it extremely hard to proceed, which makes it appear to have locked up the game, but at this time it's hard to reproduce. Once I can reproduce it reliably I will post it.

### Reproduction Steps

Example Issue 1 Steps (Shown in the video attachment)
1. Start the game and select level 1-0.
2. Begin the tutorial.
3. Press the warp/teleport button twice (or more).
4. Observe that the pieces of the tutorial you haven't reached yet start scrolling by.
5. It will stop scrolling at the checkpoint but pressing the warp/teleport button again will cause it to move forward over the checkpoint.
6. Pressing buttons may no longer work, with the exception of START, which you can use to exit the tutorial.

Example Issue 2 Steps (Shown in the attached screenshot)
1. Start the game and select level 1-0.
2. Begin the tutorial.
3. Press START and try to exit the tutorial when a tutorial dialog is about to appear (requires good timing).
4. Both the dialog showing the tutorial steps and the dialog showing the characters talking before the level ends will show up, overlapping (see screenshot).
5. Input may not correctly go to the right dialog and the tutorial may not actually exit as you have chosen. It may return to the tutorial and attempt to proceed.
6. Pressing buttons may no longer work, with the exception of START, which you can use to exit the tutorial.

### Build
Game: Development Build v0.8.2.1
OS: Tested On Mac OS X v10.12.6

### Screenshot

Video showing the tutorial level (1-0) scrolling uncontrollably. At the end of the level the ship appears to be just sitting there (after the checkpoint) but in reality I'm hitting buttons and nothing is happening. The only button (on the joystick) that still responds is START which asks if I want to continue the tutorial. This is the only way I can get out of the tutorial.
[Tutorial Warp Bug.zip](https://github.com/2awesomestudio/DimensionDriveIssueTracker/files/1184653/Tutorial.Warp.Bug.zip)

Screenshot showing overlapping menus which mess up input/flow of the tutorial:
![overlapping menus](https://user-images.githubusercontent.com/892633/28742408-406d4934-73f5-11e7-9735-ed50cdf8da2e.png)

Unity Player Log (Not showing much) from when this happens:
[Unity Player Log.zip](https://github.com/2awesomestudio/DimensionDriveIssueTracker/files/1184652/Unity.Player.Log.zip)

**Comment by alejandro-2awesome** [comment]
Tutorial is disabled for now. Closing
