### ISSUE TITLE
Times Spent Playing Each Save Game Are Not Logged

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#413]
### Description

Each save game slot shows a time which never increases and always shows 00:00:00

### Reproduction Steps
1. Create a new save game on any slot.
2. Play for a while.
3. Notice the time is still at 00:00:00 on the save game menu.

### Build
Game: Development Build v0.8.4.1
OS: Tested On Mac OS X v10.12.6

### Screenshot
![times are never logged](https://user-images.githubusercontent.com/892633/29274281-ed50bbde-80cc-11e7-9ac1-bc87b710b40d.png)

**Comment by alejandro-2awesome** [comment]
Was not yet implemented (now working fine)
