### ISSUE TITLE
Initial Game Menu Disappears After Playing A Level

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#414]
### Description

After playing any level, once you are on the level selection screen you can back out of that menu (with no input prompts shown on the HUD) and once you get to the 2nd menu (with the "Campaign" button") you will not see the menu above it on the left side of the screen.

### Reproduction Steps
1. Start any level, for example 1-1.
2. Complete the level.
3. You will be placed on the level selection screen. Instead of choosing a level, notice that there are no inputs shown on the bottom of the screen.
4. Back up three levels on the menu (B Button), observing that on each screen there are no inputs shown.
5. Once you reach the menu with "Campaign" notice the menu that should be showing on the left is missing, however, you can still back up one level (B Button) and then it will appear along with the input buttons on the HUD.

NOTE: Even the version of the game is missing on the bottom of the screen along with the input buttons.

### Build
Game: Development Build v0.8.3.1
OS: Tested On Mac OS X v10.12.6

### Screenshot
![missing menu and inputs](https://user-images.githubusercontent.com/892633/29274592-076f9b38-80ce-11e7-94bf-0b91f49c31d5.png)

And video of this happening:
[Missing Menu Bug.zip](https://github.com/2awesomestudio/DimensionDriveIssueTracker/files/1222421/Missing.Menu.Bug.zip)

**Comment by alejandro-2awesome** [comment]
Fixed: The gameobject was not enabled when coming back to LevelSelect menu (as it is done by the mainmenu object usually)
